add act condition and remove matrix filter 'function'

diff --git a/.github/workflows/ci.nftest.yml b/.github/workflows/ci.nftest.yml
--- a/.github/workflows/ci.nftest.yml
+++ b/.github/workflows/ci.nftest.yml
@@ -45,7 +45,7 @@ jobs:
           - isMaster: false
             profile: "singularity"
         shard: [1]
-        filter: ["workflow", "function", "pipeline"]
+        filter: ["workflow", "pipeline"]
     steps:
       - name: Check out pipeline code
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
@@ -101,7 +101,7 @@ jobs:
         run: |
           echo "## nf-test tests summary :rocket:" >> $GITHUB_STEP_SUMMARY
           echo "" >> $GITHUB_STEP_SUMMARY
-          echo "This \`${{ matrix.filter }}\` ${{ matrix.shard }}/5 shard was run on \`${{ matrix.profile }}\` | \`NXF_VER=${{ matrix.NXF_VER }}\`, and contains the following test(s):" >> $GITHUB_STEP_SUMMARY
+          echo "This \`${{ matrix.filter }}\` ${{ matrix.shard }}/1 shard was run on \`${{ matrix.profile }}\` | \`NXF_VER=${{ matrix.NXF_VER }}\`, and contains the following test(s):" >> $GITHUB_STEP_SUMMARY
           echo "" >> $GITHUB_STEP_SUMMARY
           nf-test test \
               --ci \
@@ -141,7 +141,7 @@ jobs:
 
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
-        if: success() || failure() # always run even if the previous step fails
+        if: (success() || failure()) && !github.event.act # always run even if the previous step fails
         with:
           report_paths: "TEST-*.xml"
 
